source 'https://rubygems.org'
gem 'rack-cors'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'unicorn'
gem 'pg'
gem 'algoliasearch'
gem 'wannabe_bool'
gem 'jwt'
gem 'sinatra-subdomain'
gem 'slugify'
# gem 'twilio-ruby'
