require 'sinatra/base'
require 'sinatra/reloader'
require 'date'
require 'erb'
require 'cgi'
require 'pg'
require 'sinatra/subdomain'
require 'rack/csrf'
require 'encrypted_cookie'
require 'redis'
# require 'twilio-ruby'
include ERB::Util
