PGHOST="127.0.0.1"
PGPORT="5432" 
PGPWD="DB_PASSWORD"
PGNAME="DB_NAME"
PGUSER="DB_USER"
ALGOLIA_ID="ALGOLIA_ID"
ALGOLIA_KEY="ALGOLIA_KEY"
AWS_S3_BUCKET_URL="https://s3.eu-central-1.amazonaws.com/laprimaire/"
TWLSID="KSLFKSDLKFSLFKDSLK" # Twilio SID
TWLTOKEN="isfdskfjSDFSFsdfsdf" #Twilio Token
CC_HOST="https://cocorico.cc"
CC_APP_ID="57cc8c8b43572b6b55ad6d35"
CC_SECRET="pjqtswkgp34y40i9jcvyojo49pyj6eln"
CC_HOST_TEST="https://test.cocorico.cc"
CC_APP_ID_TEST="58006cc3ed46e661d1387f7f"
CC_SECRET_TEST="9iys-emrnhneic4powyhaxk78vnmu1wl"
ABANDONS=[]
EXCLUSIONS=[]
RETRAITS=[]
